internalName: niv

locales:
  en:
    name: &bundleName "Nivkh Keyboards"
    description: "Keyboards for the Nivkh language."
  nb:
    name: "Nivkh-tastatur"
    description: "Mobiltastatur for Nivkh."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [niv-mobile, niv-mac, niv-win]

version: 1.0.1
build: 2

targets:
  android:
    packageId: no.uit.giella.keyboards.niv
    icon: images/niv-app-icon.png
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.niv
    bundleName: *bundleName
    icon: images/niv-app-icon.png

  osx:
    <<: *AppleID
    icon: images/niv-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "91409358-C300-4933-A565-328B5085357D"
